### Webscraping Bonus

>1. Navigate to https://www.billboard.com/charts/hot-100/. Using BeautifulSoup, extract out the This Week, artist, song, Last Week, Peak Position, and Weeks on Chart values into a pandas DataFrame. Hint: The HTML for the number one ranked song is slightly different from that of the rest of the songs.
>
>2. After getting the code working for the current chart, navigate to last week's chart. Notice how the url for the page changes. Write a function which will, given a date, return a pandas DataFrame containing the Billboard chart data for that date.
>
>3. Write a loop to retrieve the Billboard chart data for the last 10 weeks.

In [1]:
import requests
from bs4 import BeautifulSoup as BS
import pandas as pd
import re
from IPython.display import display

In [2]:
URL = 'https://www.billboard.com/charts/hot-100/'

response = requests.get(URL)

In [3]:
response.status_code

200

In [4]:
soup = BS(response.text)

In [5]:
ranks = soup.findAll('span', attrs={'class' : 'u-line-height-33px'})
rank_this_week = [x.get_text(strip=True) for x in ranks]
rank_this_week

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97',
 '98',
 '99',
 '100']

In [6]:
artists = soup.findAll('span', attrs={'class' : 'u-line-height-21px'})
artist_this_week = [x.get_text(strip=True) for x in artists]
artist_this_week

['HUNTR/X: EJAE, Audrey Nuna & REI AMI',
 'Alex Warren',
 'Tate McRae',
 'Morgan WallenFeaturingTate McRae',
 'Justin Bieber',
 'Teddy Swims',
 'Saja Boys: Andrew Choi, Neckwav, Danny Chung, Kevin Woo & samUIL Lee',
 'Morgan Wallen',
 'Ravyn Lenae',
 'Saja Boys: Andrew Choi, Neckwav, Danny Chung, Kevin Woo & samUIL Lee',
 'Leon Thomas',
 'Olivia Dean',
 'Lady Gaga&Bruno Mars',
 'Sabrina Carpenter',
 'Benson Boone',
 'Shaboozey',
 'HUNTR/X: EJAE, Audrey Nuna & REI AMI',
 'Kehlani',
 'Morgan Wallen',
 'Chappell Roan',
 'sombr',
 'sombr',
 'Shaboozey',
 'Sabrina Carpenter',
 'Morgan Wallen',
 'Benson Boone',
 'HUNTR/X: EJAE, Audrey Nuna & REI AMI',
 'Kendrick Lamar&SZA',
 'Chris BrownFeaturingBryson Tiller',
 'HUNTR/X: EJAE, Audrey Nuna & REI AMI',
 'Rumi, JINU, EJAE & Andrew Choi',
 'Scotty McCreery& Hootie & The Blowfish',
 'Justin Bieber',
 'Mariah the Scientist',
 'Sabrina Carpenter',
 'Doja Cat',
 'BigXthaPlug FeaturingBailey Zimmerman',
 'Luke Combs',
 'Russell Dickerson',
 'Benson Boone',
 'Jordan Davis',
 'Cardi BFeaturingKehlani',
 'Cardi B',
 'Disco Lines &Tinashe',
 'Tate McRae',
 'Tyler, the Creator',
 'Riley Green',
 'BigXthaPlug Featuring Ella Langley',
 'sombr',
 'KATSEYE',
 'Hudson Westbrook',
 'Megan Moroney',
 'Jelly Roll',
 'Billie Eilish',
 'Tame Impala',
 'Doja Cat',
 'Cardi B',
 'Lainey Wilson',
 'Cardi B',
 'Cardi B',
 'Lady Gaga',
 'Sabrina Carpenter',
 'JEONGYEON, JIHYO & CHAEYOUNG Of TWICE',
 'YoungBoy Never Broke Again',
 'Tate McRae',
 'Twice',
 'Max McNown',
 'Riley GreenFeaturing Ella Langley',
 'Young Thug',
 'Fuerza Regida',
 'Gavin Adcock',
 'Mariah the Scientist&Kali Uchis',
 'Myles Smith',
 'Alex Warren',
 'GunnaFeaturingBurna Boy',
 'Cardi B',
 'Chappell Roan',
 'The Marias',
 'Coldplay',
 'Ed Sheeran',
 'Chase Matthew',
 'Rihanna',
 'Sabrina Carpenter',
 'Morgan Wallen',
 'G Herbo',
 'Cody Johnson',
 'Drake& Central Cee',
 'Cardi BFeaturingSummer Walker',
 'Cardi B',
 'RAYE',
 'Radiohead',
 'Cardi BFeaturingLizzo',
 'Cardi BFeaturingSelena Gomez',
 'Parker McCollum',
 'KATSEYE',
 'Bad Bunny',
 'Olivia Dean',
 'Olivia Dean',
 'Metro Boomin,Quavo, Breskii & YK NIECE',
 'Phil Wickham']

In [7]:
songs = soup.findAll('h3', attrs={'class' : 'u-line-height-22px'})
song_this_week = [x.get_text(strip=True) for x in songs]
song_this_week

['Golden',
 'Ordinary',
 'Tit For Tat',
 'What I Want',
 'Daisies',
 'Lose Control',
 'Soda Pop',
 'I Got Better',
 'Love Me Not',
 'Your Idol',
 'Mutt',
 'Man I Need',
 'Die With A Smile',
 'Manchild',
 'Beautiful Things',
 'A Bar Song (Tipsy)',
 "How It's Done",
 'Folded',
 'Just In Case',
 'Pink Pony Club',
 'Undressed',
 'Back To Friends',
 'Good News',
 'Tears',
 "I'm The Problem",
 'Mystical Magical',
 'What It Sounds Like',
 'Luther',
 'It Depends',
 'Takedown',
 'Free',
 'Bottle Rockets',
 'Yukon',
 'Burning Blue',
 'When Did You Get Hot?',
 'Jealous Type',
 'All The Way',
 'Back In The Saddle',
 'Happen To Me',
 "Sorry I'm Here For Someone Else",
 'Bar None',
 'Safe',
 'ErrTime',
 'No Broke Boys',
 'Revolving Door',
 'Sugar On My Tongue',
 'Worst Way',
 'Hell At Night',
 '12 To 12',
 'Gabriela',
 'House Again',
 '6 Months Later',
 'Heart Of Stone',
 'Wildflower',
 'Dracula',
 'Gorgeous',
 'Outside',
 'Somewhere Over Laredo',
 'Pretty & Petty',
 'Magnet',
 'The Dead Dance',
 "Nobody's Son",
 'Takedown',
 'Shot Callin',
 'Just Keep Watching',
 'Strategy',
 'Better Me For You (Brown Eyes)',
 "Don't Mind If I Do",
 'Ninja',
 'Marlboro Rojo',
 'Last One To Know',
 'Is It A Crime',
 'Nice To Meet You',
 'Eternity',
 'wgft',
 'Hello',
 'The Subway',
 'Sienna',
 'Sparks',
 'Camera',
 "Darlin'",
 "Breakin' Dishes",
 'House Tour',
 '20 Cigarettes',
 'Went Legit',
 'The Fall',
 'Which One',
 'Dead',
 'Bodega Baddie',
 'Where Is My Husband!',
 'Let Down',
 "What's Goin On",
 'Pick It Up',
 'What Kinda Man',
 'Gnarly',
 'Voy A Llevarte Pa PR',
 'Nice To Each Other',
 'So Easy (To Fall In Love)',
 'Take Me Thru Dere',
 'What An Awesome God']

In [8]:
other_ranks_and_weeks = soup.findAll('span', attrs={'class' : 'u-min-width-30px'})
weeks_and_other_ranks = [x.get_text(strip=True) for x in other_ranks_and_weeks]
weeks_and_other_ranks

['1',
 '1',
 '15',
 '1',
 '1',
 '15',
 '2',
 '1',
 '34',
 '2',
 '1',
 '34',
 '-',
 '3',
 '1',
 '-',
 '3',
 '1',
 '4',
 '1',
 '20',
 '4',
 '1',
 '20',
 '8',
 '2',
 '12',
 '8',
 '2',
 '12',
 '7',
 '1',
 '111',
 '7',
 '1',
 '111',
 '3',
 '3',
 '14',
 '3',
 '3',
 '14',
 '11',
 '7',
 '20',
 '11',
 '7',
 '20',
 '9',
 '5',
 '27',
 '9',
 '5',
 '27',
 '5',
 '4',
 '15',
 '5',
 '4',
 '15',
 '12',
 '11',
 '35',
 '12',
 '11',
 '35',
 '25',
 '12',
 '6',
 '25',
 '12',
 '6',
 '10',
 '1',
 '59',
 '10',
 '1',
 '59',
 '6',
 '1',
 '17',
 '6',
 '1',
 '17',
 '14',
 '2',
 '88',
 '14',
 '2',
 '88',
 '15',
 '1',
 '77',
 '15',
 '1',
 '77',
 '13',
 '8',
 '14',
 '13',
 '8',
 '14',
 '22',
 '18',
 '16',
 '22',
 '18',
 '16',
 '18',
 '2',
 '28',
 '18',
 '2',
 '28',
 '19',
 '4',
 '68',
 '19',
 '4',
 '68',
 '16',
 '16',
 '26',
 '16',
 '16',
 '26',
 '23',
 '22',
 '27',
 '23',
 '22',
 '27',
 '20',
 '12',
 '45',
 '20',
 '12',
 '45',
 '17',
 '3',
 '5',
 '17',
 '3',
 '5',
 '24',
 '2',
 '35',
 '24',
 '2',
 '35',
 '27',
 '17',
 '23',
 '27',
 '17',
 '23',
 '21',
 '15',
 '14',
 '21',
 '15',
 '14',
 '28',
 '1',
 '45',
 '28',
 '1',
 '45',
 '31',
 '29',
 '10',
 '31',
 '29',
 '10',
 '29',
 '21',
 '14',
 '29',
 '21',
 '14',
 '30',
 '23',
 '14',
 '30',
 '23',
 '14',
 '33',
 '32',
 '15',
 '33',
 '32',
 '15',
 '35',
 '17',
 '12',
 '35',
 '17',
 '12',
 '34',
 '25',
 '22',
 '34',
 '25',
 '22',
 '32',
 '17',
 '5',
 '32',
 '17',
 '5',
 '57',
 '28',
 '6',
 '57',
 '28',
 '6',
 '36',
 '4',
 '26',
 '36',
 '4',
 '26',
 '54',
 '38',
 '10',
 '54',
 '38',
 '10',
 '40',
 '28',
 '24',
 '40',
 '28',
 '24',
 '39',
 '19',
 '31',
 '39',
 '19',
 '31',
 '44',
 '41',
 '13',
 '44',
 '41',
 '13',
 '26',
 '26',
 '2',
 '26',
 '26',
 '2',
 '65',
 '43',
 '2',
 '65',
 '43',
 '2',
 '41',
 '39',
 '12',
 '41',
 '39',
 '12',
 '52',
 '22',
 '25',
 '52',
 '22',
 '25',
 '55',
 '41',
 '11',
 '55',
 '41',
 '11',
 '50',
 '20',
 '38',
 '50',
 '20',
 '38',
 '49',
 '35',
 '8',
 '49',
 '35',
 '8',
 '48',
 '41',
 '7',
 '48',
 '41',
 '7',
 '56',
 '45',
 '11',
 '56',
 '45',
 '11',
 '58',
 '51',
 '24',
 '58',
 '51',
 '24',
 '62',
 '30',
 '15',
 '62',
 '30',
 '15',
 '64',
 '53',
 '7',
 '64',
 '53',
 '7',
 '61',
 '17',
 '68',
 '61',
 '17',
 '68',
 '-',
 '55',
 '1',
 '-',
 '55',
 '1',
 '-',
 '56',
 '1',
 '-',
 '56',
 '1',
 '42',
 '10',
 '15',
 '42',
 '10',
 '15',
 '59',
 '54',
 '13',
 '59',
 '54',
 '13',
 '43',
 '43',
 '2',
 '43',
 '43',
 '2',
 '37',
 '37',
 '2',
 '37',
 '37',
 '2',
 '60',
 '40',
 '4',
 '60',
 '40',
 '4',
 '51',
 '12',
 '5',
 '51',
 '12',
 '5',
 '68',
 '50',
 '13',
 '68',
 '50',
 '13',
 '84',
 '64',
 '3',
 '84',
 '64',
 '3',
 '67',
 '33',
 '18',
 '67',
 '33',
 '18',
 '69',
 '51',
 '11',
 '69',
 '51',
 '11',
 '72',
 '50',
 '16',
 '72',
 '50',
 '16',
 '79',
 '68',
 '9',
 '79',
 '68',
 '9',
 '-',
 '69',
 '1',
 '-',
 '69',
 '1',
 '80',
 '64',
 '20',
 '80',
 '64',
 '20',
 '74',
 '71',
 '7',
 '74',
 '71',
 '7',
 '83',
 '59',
 '8',
 '83',
 '59',
 '8',
 '82',
 '73',
 '17',
 '82',
 '73',
 '17',
 '78',
 '16',
 '11',
 '78',
 '16',
 '11',
 '76',
 '66',
 '8',
 '76',
 '66',
 '8',
 '46',
 '46',
 '2',
 '46',
 '46',
 '2',
 '75',
 '3',
 '9',
 '75',
 '3',
 '9',
 '87',
 '74',
 '4',
 '87',
 '74',
 '4',
 '86',
 '77',
 '12',
 '86',
 '77',
 '12',
 '93',
 '58',
 '3',
 '93',
 '58',
 '3',
 '98',
 '81',
 '2',
 '98',
 '81',
 '2',
 '89',
 '82',
 '3',
 '89',
 '82',
 '3',
 '71',
 '27',
 '5',
 '71',
 '27',
 '5',
 '91',
 '20',
 '20',
 '91',
 '20',
 '20',
 '99',
 '81',
 '11',
 '99',
 '81',
 '11',
 '-',
 '86',
 '1',
 '-',
 '86',
 '1',
 '96',
 '23',
 '10',
 '96',
 '23',
 '10',
 '47',
 '47',
 '2',
 '47',
 '47',
 '2',
 '53',
 '53',
 '2',
 '53',
 '53',
 '2',
 '-',
 '90',
 '1',
 '-',
 '90',
 '1',
 '-',
 '91',
 '6',
 '-',
 '91',
 '6',
 '63',
 '63',
 '2',
 '63',
 '63',
 '2',
 '45',
 '45',
 '2',
 '45',
 '45',
 '2',
 '-',
 '94',
 '3',
 '-',
 '94',
 '3',
 '-',
 '90',
 '9',
 '-',
 '90',
 '9',
 '-',
 '17',
 '12',
 '-',
 '17',
 '12',
 '-',
 '97',
 '1',
 '-',
 '97',
 '1',
 '-',
 '98',
 '1',
 '-',
 '98',
 '1',
 '-',
 '99',
 '1',
 '-',
 '99',
 '1',
 '-',
 '100',
 '1',
 '-',
 '100',
 '1']

In [9]:
last_week = []
if weeks_and_other_ranks:
    # Add the first element's text
    last_week.append(weeks_and_other_ranks[0])

    # Iterate from the third element (index 2) and take every third one
    for i in range(6, len(weeks_and_other_ranks), 6):
        last_week.append(weeks_and_other_ranks[i])

last_week

['1',
 '2',
 '-',
 '4',
 '8',
 '7',
 '3',
 '11',
 '9',
 '5',
 '12',
 '25',
 '10',
 '6',
 '14',
 '15',
 '13',
 '22',
 '18',
 '19',
 '16',
 '23',
 '20',
 '17',
 '24',
 '27',
 '21',
 '28',
 '31',
 '29',
 '30',
 '33',
 '35',
 '34',
 '32',
 '57',
 '36',
 '54',
 '40',
 '39',
 '44',
 '26',
 '65',
 '41',
 '52',
 '55',
 '50',
 '49',
 '48',
 '56',
 '58',
 '62',
 '64',
 '61',
 '-',
 '-',
 '42',
 '59',
 '43',
 '37',
 '60',
 '51',
 '68',
 '84',
 '67',
 '69',
 '72',
 '79',
 '-',
 '80',
 '74',
 '83',
 '82',
 '78',
 '76',
 '46',
 '75',
 '87',
 '86',
 '93',
 '98',
 '89',
 '71',
 '91',
 '99',
 '-',
 '96',
 '47',
 '53',
 '-',
 '-',
 '63',
 '45',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-']

In [10]:
peak = []
if weeks_and_other_ranks:
    # Add the first element's text
    peak.append(weeks_and_other_ranks[1])

    # Iterate from the third element (index 2) and take every third one
    for i in range(7, len(weeks_and_other_ranks), 6):
        peak.append(weeks_and_other_ranks[i])

peak

['1',
 '1',
 '3',
 '1',
 '2',
 '1',
 '3',
 '7',
 '5',
 '4',
 '11',
 '12',
 '1',
 '1',
 '2',
 '1',
 '8',
 '18',
 '2',
 '4',
 '16',
 '22',
 '12',
 '3',
 '2',
 '17',
 '15',
 '1',
 '29',
 '21',
 '23',
 '32',
 '17',
 '25',
 '17',
 '28',
 '4',
 '38',
 '28',
 '19',
 '41',
 '26',
 '43',
 '39',
 '22',
 '41',
 '20',
 '35',
 '41',
 '45',
 '51',
 '30',
 '53',
 '17',
 '55',
 '56',
 '10',
 '54',
 '43',
 '37',
 '40',
 '12',
 '50',
 '64',
 '33',
 '51',
 '50',
 '68',
 '69',
 '64',
 '71',
 '59',
 '73',
 '16',
 '66',
 '46',
 '3',
 '74',
 '77',
 '58',
 '81',
 '82',
 '27',
 '20',
 '81',
 '86',
 '23',
 '47',
 '53',
 '90',
 '91',
 '63',
 '45',
 '94',
 '90',
 '17',
 '97',
 '98',
 '99',
 '100']

In [11]:
weeks = []
if weeks_and_other_ranks:
    # Add the first element's text
    weeks.append(weeks_and_other_ranks[2])

    # Iterate from the third element (index 2) and take every third one
    for i in range(8, len(weeks_and_other_ranks), 6):
        weeks.append(weeks_and_other_ranks[i])

weeks

['15',
 '34',
 '1',
 '20',
 '12',
 '111',
 '14',
 '20',
 '27',
 '15',
 '35',
 '6',
 '59',
 '17',
 '88',
 '77',
 '14',
 '16',
 '28',
 '68',
 '26',
 '27',
 '45',
 '5',
 '35',
 '23',
 '14',
 '45',
 '10',
 '14',
 '14',
 '15',
 '12',
 '22',
 '5',
 '6',
 '26',
 '10',
 '24',
 '31',
 '13',
 '2',
 '2',
 '12',
 '25',
 '11',
 '38',
 '8',
 '7',
 '11',
 '24',
 '15',
 '7',
 '68',
 '1',
 '1',
 '15',
 '13',
 '2',
 '2',
 '4',
 '5',
 '13',
 '3',
 '18',
 '11',
 '16',
 '9',
 '1',
 '20',
 '7',
 '8',
 '17',
 '11',
 '8',
 '2',
 '9',
 '4',
 '12',
 '3',
 '2',
 '3',
 '5',
 '20',
 '11',
 '1',
 '10',
 '2',
 '2',
 '1',
 '6',
 '2',
 '2',
 '3',
 '9',
 '12',
 '1',
 '1',
 '1',
 '1']

In [12]:
data = {
    'This Week' : rank_this_week,
    'Artist' : artist_this_week,
    'Song' : song_this_week,
    'Last Week' : last_week,
    'Peak' : peak,
    'Weeks on Chart' : weeks 
}

In [13]:
billboard = pd.DataFrame(data)

In [14]:
billboard

,This Week,Artist,Song,Last Week,Peak,Weeks on Chart
0,1,"HUNTR/X: EJAE, Audrey Nuna & REI AMI",Golden,1,1,15
1,2,Alex Warren,Ordinary,2,1,34
2,3,Tate McRae,Tit For Tat,-,3,1
3,4,Morgan WallenFeaturingTate McRae,What I Want,4,1,20
4,5,Justin Bieber,Daisies,8,2,12
...,...,...,...,...,...,...
95,96,Bad Bunny,Voy A Llevarte Pa PR,-,17,12
96,97,Olivia Dean,Nice To Each Other,-,97,1
97,98,Olivia Dean,So Easy (To Fall In Love),-,98,1
98,99,"Metro Boomin,Quavo, Breskii & YK NIECE",Take Me Thru Dere,-,99,1
99,100,Phil Wickham,What An Awesome God,-,100,1

In [47]:
def get_billboard_chart(chart_week):
    """
    Scrapes a single week's Billboard Hot 100 chart and returns a DataFrame.
    """
    try:

        URL = f"https://www.billboard.com/charts/hot-100/{chart_week}/"
        response = requests.get(URL)
        response.raise_for_status() #raises error for bad status
        soup = BS(response.text)
    
        ranks = soup.findAll('span', attrs={'class' : 'u-line-height-33px'})
        rank_this_week = [x.get_text(strip=True) for x in ranks]
    
        artists = soup.findAll('span', attrs={'class' : 'u-line-height-21px'})
        artist_this_week = [x.get_text(strip=True) for x in artists]
    
        songs = soup.findAll('h3', attrs={'class' : 'u-line-height-22px'})
        song_this_week = [x.get_text(strip=True) for x in songs]
    
        other_ranks_and_weeks = soup.findAll('span', attrs={'class' : 'u-min-width-30px'})
        weeks_and_other_ranks = [x.get_text(strip=True) for x in other_ranks_and_weeks]
    
        last_week = []
        if weeks_and_other_ranks:
            # Add the first element's text
            last_week.append(weeks_and_other_ranks[0])
        
            # Iterate from the third element (index 2) and take every third one
            for i in range(6, len(weeks_and_other_ranks), 6):
                last_week.append(weeks_and_other_ranks[i])
        
        
        peak = []
        if weeks_and_other_ranks:
            # Add the first element's text
            peak.append(weeks_and_other_ranks[1])
        
            # Iterate from the third element (index 2) and take every third one
            for i in range(7, len(weeks_and_other_ranks), 6):
                peak.append(weeks_and_other_ranks[i])
        
        weeks = []
        if weeks_and_other_ranks:
            # Add the first element's text
            weeks.append(weeks_and_other_ranks[2])
        
            # Iterate from the third element (index 2) and take every third one
            for i in range(8, len(weeks_and_other_ranks), 6):
                weeks.append(weeks_and_other_ranks[i])
    
        data = {
            'This Week' : rank_this_week,
            'Artist' : artist_this_week,
            'Song' : song_this_week,
            'Last Week' : last_week,
            'Peak' : peak,
            'Weeks on Chart' : weeks 
        }
    
        df = pd.DataFrame(data)

        return df
    except Exception as e:
        print(f"Error scraping {chart_week}: {e}")
        return None

In [48]:
get_billboard_chart('2025-10-04')

,This Week,Artist,Song,Last Week,Peak,Weeks on Chart
0,1,"HUNTR/X: EJAE, Audrey Nuna & REI AMI",Golden,1,1,14
1,2,Alex Warren,Ordinary,2,1,33
2,3,"Saja Boys: Andrew Choi, Neckwav, Danny Chung, ...",Soda Pop,5,3,13
3,4,Morgan WallenFeaturingTate McRae,What I Want,4,1,19
4,5,"Saja Boys: Andrew Choi, Neckwav, Danny Chung, ...",Your Idol,6,4,14
...,...,...,...,...,...,...
95,96,Drake& Central Cee,Which One,99,23,9
96,97,Sabrina Carpenter,Goodbye,70,33,4
97,98,Chase Matthew,Darlin',-,98,1
98,99,G Herbo,Went Legit,-,81,10
99,100,Drake,What Did I Miss?,80,2,12

In [51]:
from datetime import date, timedelta

def get_past_saturdays(num_saturdays):
    """
    Generates a list of date strings for the past 'num_saturdays' Saturdays.
    """
    today = date.today()
    saturdays = []

    # Find the most recent Saturday (could be today if today is Saturday)
    # weekday() returns 0 for Monday, 6 for Sunday. Saturday is 5.
    days_since_saturday = (today.weekday() - 5 + 7) % 7
    last_saturday = today - timedelta(days=days_since_saturday)

    for i in range(num_saturdays):
        current_saturday = last_saturday - timedelta(weeks=i)
        saturdays.append(current_saturday.isoformat()) # Format as YYYY-MM-DD
    return saturdays

# Get the past 10 Saturdays
past_10_saturdays = get_past_saturdays(10)

# Loop through the dates and pass them to the function
for saturday_date_str in past_10_saturdays:
    chart_df = get_billboard_chart(saturday_date_str)
    if chart_df is not None:
        print(f"\n--- Billboard Chart for {saturday_date_str} ---\n")
        display(chart_df)

--- Billboard Chart for 2025-10-04 ---

,This Week,Artist,Song,Last Week,Peak,Weeks on Chart
0,1,"HUNTR/X: EJAE, Audrey Nuna & REI AMI",Golden,1,1,14
1,2,Alex Warren,Ordinary,2,1,33
2,3,"Saja Boys: Andrew Choi, Neckwav, Danny Chung, ...",Soda Pop,5,3,13
3,4,Morgan WallenFeaturingTate McRae,What I Want,4,1,19
4,5,"Saja Boys: Andrew Choi, Neckwav, Danny Chung, ...",Your Idol,6,4,14
...,...,...,...,...,...,...
95,96,Drake& Central Cee,Which One,99,23,9
96,97,Sabrina Carpenter,Goodbye,70,33,4
97,98,Chase Matthew,Darlin',-,98,1
98,99,G Herbo,Went Legit,-,81,10
99,100,Drake,What Did I Miss?,80,2,12

--- Billboard Chart for 2025-09-27 ---

,This Week,Artist,Song,Last Week,Peak,Weeks on Chart
0,1,"HUNTR/X: EJAE, Audrey Nuna & REI AMI",Golden,1,1,13
1,2,Alex Warren,Ordinary,2,1,32
2,3,Sabrina Carpenter,Manchild,3,1,15
3,4,Morgan WallenFeaturingTate McRae,What I Want,7,1,18
4,5,"Saja Boys: Andrew Choi, Neckwav, Danny Chung, ...",Soda Pop,5,5,12
...,...,...,...,...,...,...
95,96,Key Glock,She Ready,91,91,3
96,97,KATSEYE,Gnarly,-,90,8
97,98,Morgan WallenFeaturingPost Malone,I Ain't Coming Back,97,8,22
98,99,Drake& Central Cee,Which One,98,23,8
99,100,Radiohead,Let Down,95,91,5

--- Billboard Chart for 2025-09-20 ---

,This Week,Artist,Song,Last Week,Peak,Weeks on Chart
0,1,"HUNTR/X: EJAE, Audrey Nuna & REI AMI",Golden,1,1,12
1,2,Alex Warren,Ordinary,2,1,31
2,3,Sabrina Carpenter,Manchild,4,1,14
3,4,"Saja Boys: Andrew Choi, Neckwav, Danny Chung, ...",Your Idol,5,4,12
4,5,"Saja Boys: Andrew Choi, Neckwav, Danny Chung, ...",Soda Pop,6,5,11
...,...,...,...,...,...,...
95,96,Cardi B,Outside,88,10,12
96,97,Morgan WallenFeaturingPost Malone,I Ain't Coming Back,87,8,21
97,98,Drake& Central Cee,Which One,96,23,7
98,99,Morgan WallenFeaturingLil Wayne&Rick Ross,Miami,85,21,10
99,100,Pierce the Veil,So Far So Fake,92,64,6

--- Billboard Chart for 2025-09-13 ---

,This Week,Artist,Song,Last Week,Peak,Weeks on Chart
0,1,"HUNTR/X: EJAE, Audrey Nuna & REI AMI",Golden,1,1,11
1,2,Alex Warren,Ordinary,2,1,30
2,3,Sabrina Carpenter,Tears,-,3,1
3,4,Sabrina Carpenter,Manchild,7,1,13
4,5,"Saja Boys: Andrew Choi, Neckwav, Danny Chung, ...",Your Idol,4,4,11
...,...,...,...,...,...,...
95,96,Drake& Central Cee,Which One,84,23,6
96,97,Key Glock,She Ready,-,97,1
97,98,Zach Top,South Of Sanity,-,98,1
98,99,Offset&Gunna,Different Species,73,73,2
99,100,KATSEYE,Gnarly,98,90,7

--- Billboard Chart for 2025-09-06 ---

,This Week,Artist,Song,Last Week,Peak,Weeks on Chart
0,1,"HUNTR/X: EJAE, Audrey Nuna & REI AMI",Golden,1,1,10
1,2,Alex Warren,Ordinary,2,1,29
2,3,Morgan WallenFeaturingTate McRae,What I Want,3,1,15
3,4,"Saja Boys: Andrew Choi, Neckwav, Danny Chung, ...",Your Idol,4,4,10
4,5,"Saja Boys: Andrew Choi, Neckwav, Danny Chung, ...",Soda Pop,5,5,9
...,...,...,...,...,...,...
95,96,"Tyler, the Creator",Ring Ring Ring,85,44,6
96,97,Alex WarrenWithJelly Roll,Bloodline,94,32,13
97,98,KATSEYE,Gnarly,-,90,6
98,99,Fuerza Regida,Tu Sancho,92,65,10
99,100,Parker McCollum,What Kinda Man,98,98,2

--- Billboard Chart for 2025-08-30 ---

,This Week,Artist,Song,Last Week,Peak,Weeks on Chart
0,1,"HUNTR/X: EJAE, Audrey Nuna & REI AMI",Golden,2,1,9
1,2,Alex Warren,Ordinary,1,1,28
2,3,Morgan WallenFeaturingTate McRae,What I Want,3,1,14
3,4,"Saja Boys: Andrew Choi, Neckwav, Danny Chung, ...",Your Idol,4,4,9
4,5,"Saja Boys: Andrew Choi, Neckwav, Danny Chung, ...",Soda Pop,10,5,8
...,...,...,...,...,...,...
95,96,GunnaFeaturingWizkid,Forever Be Mine,68,68,2
96,97,Latto,Somebody,-,97,2
97,98,Parker McCollum,What Kinda Man,-,98,1
98,99,Luke Bryan,Country Song Came On,93,93,3
99,100,$uicideboy$,Napoleon,95,54,3

--- Billboard Chart for 2025-08-23 ---

,This Week,Artist,Song,Last Week,Peak,Weeks on Chart
0,1,Alex Warren,Ordinary,2,1,27
1,2,"HUNTR/X: EJAE, Audrey Nuna & REI AMI",Golden,1,1,8
2,3,Morgan WallenFeaturingTate McRae,What I Want,4,1,13
3,4,"Saja Boys: Andrew Choi, Neckwav, Danny Chung, ...",Your Idol,8,4,8
4,5,Ravyn Lenae,Love Me Not,6,5,20
...,...,...,...,...,...,...
95,96,Brandon LakeX Jelly Roll,Hard Fought Hallelujah,87,40,26
96,97,Morgan Wallen,TN,76,31,13
97,98,G Herbo,Went Legit,89,81,6
98,99,Gunna,Many Nights,-,99,1
99,100,Glorilla,Typa,92,42,9

--- Billboard Chart for 2025-08-16 ---

,This Week,Artist,Song,Last Week,Peak,Weeks on Chart
0,1,"HUNTR/X: EJAE, Audrey Nuna & REI AMI",Golden,2,1,7
1,2,Alex Warren,Ordinary,1,1,26
2,3,Chappell Roan,The Subway,-,3,1
3,4,Morgan WallenFeaturingTate McRae,What I Want,3,1,12
4,5,Justin Bieber,Daisies,4,2,4
...,...,...,...,...,...,...
95,96,Tyler Hubbard,Park,84,84,2
96,97,Max McNown,A Lot More Free,-,97,1
97,98,Luke Bryan,Country Song Came On,-,98,1
98,99,Latto,Somebody,-,99,1
99,100,$uicideboy$ X BONES,Now And At The Hour Of Our Death..,-,100,1

--- Billboard Chart for 2025-08-09 ---

,This Week,Artist,Song,Last Week,Peak,Weeks on Chart
0,1,Alex Warren,Ordinary,1,1,25
1,2,"HUNTR/X: EJAE, Audrey Nuna & REI AMI",Golden,2,2,6
2,3,Morgan WallenFeaturingTate McRae,What I Want,4,1,11
3,4,Justin Bieber,Daisies,3,2,3
4,5,Morgan Wallen,Just In Case,5,2,19
...,...,...,...,...,...,...
95,96,Zach BryanFeaturing Gabriella Rose,Madeline,62,62,2
96,97,"Tyler, the Creator",Mommanem,54,54,2
97,98,Zach Bryan,River Washed Hair,90,53,4
98,99,"Tyler, the Creator",Don't Tap That Glass / Tweakin',56,56,2
99,100,Fuerza Regida,Tu Sancho,-,65,7

--- Billboard Chart for 2025-08-02 ---

,This Week,Artist,Song,Last Week,Peak,Weeks on Chart
0,1,Alex Warren,Ordinary,1,1,24
1,2,"HUNTR/X: EJAE, Audrey Nuna & REI AMI",Golden,4,2,5
2,3,Justin Bieber,Daisies,2,2,2
3,4,Morgan WallenFeaturingTate McRae,What I Want,3,1,10
4,5,Morgan Wallen,Just In Case,5,2,18
...,...,...,...,...,...,...
95,96,Myles Smith,Nice To Meet You,-,82,7
96,97,Bad Bunny,Nuevayol,96,8,19
97,98,Playboi Carti&The Weeknd,Rather Lie,99,4,19
98,99,Lainey Wilson,Somewhere Over Laredo,-,88,3
99,100,Glorilla,Typa,-,42,6